name: Actualizar IPTV Canales

on:
  schedule:
    - cron: '0 */4 * * *' # Se ejecuta cada 4 horas automáticamente
  workflow_dispatch: # Permite lanzarlo manualmente cuando quieras

jobs:
  run-extractor:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script extractor
        run: python extractor.py

      - name: Commit y Push de los cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u
          git commit -m "Actualización automática de canales M3U [skip ci]" || echo "Sin cambios"
          git push
